# Generated by Django 6.0.4 on 2026-05-01 02:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disaster',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='report',
            name='type',
            field=models.CharField(default='Other', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='disaster',
            name='severity',
            field=models.CharField(choices=[('Low', 'Low'), ('Mild', 'Mild'), ('High', 'High'), ('Severe', 'Severe')], max_length=20),
        ),
        migrations.AlterField(
            model_name='disaster',
            name='type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('pending', 'Pending'), ('resolved', 'Resolved')], default='submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='disaster_app.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('resident', 'Resident'), ('admin', 'Admin')], default='resident', max_length=20),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('is_sos', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='disaster_app.user')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
