# Generated by Django 5.2.5 on 2026-05-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster_app', '0002_alter_disaster_options_alter_report_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='form_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='report',
            name='source_page',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='form_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='request',
            name='source_page',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
